### ISSUE TITLE
Oscar Rojas G.

### ISSUE THREAD

**Issue by OscarRojasG** [sgarciaddev/ayudantia-ingweb-012024#23]
https://github.com/OscarRojasG

**Comment by sgarciaddev** [comment]
Hola Oscar! :hand: Bienvenido al repo de la ayudantía del curso :octocat: próximamente te daré acceso al **GitHub Project** de la ayudantía, para que le puedas pegar una mirada :100: :eyes:

Saludos! :star_struck:
