### ISSUE TITLE
Hola, soy Carlos da silva deseo ingresar a su github

### ISSUE THREAD

**Issue by davlobos** [sgarciaddev/ayudantia-ingweb-012024#27]
Soy alumno de Ingeniería web y escribo para ingresar a su github

**Comment by sgarciaddev** [comment]
Hola Carlos! :hand: Bienvenido al repo de la ayudantía del curso :octocat: próximamente te daré acceso al **GitHub Project** de la ayudantía, para que le puedas pegar una mirada :100: :eyes:

Saludos! :star_struck:
