### ISSUE TITLE
Solicitud de unirse

### ISSUE THREAD

**Issue by Leftzara** [sgarciaddev/ayudantia-ingweb-012024#28]
Saludos ayudante, soy Nicolás Zárate de ingenieria web.

**Comment by sgarciaddev** [comment]
Hola Nicolás! :hand: Bienvenido al repo de la ayudantía del curso :octocat: próximamente te daré acceso al **GitHub Project** de la ayudantía, para que le puedas pegar una mirada :100: :eyes:

Saludos! :star_struck:
