### ISSUE TITLE
Issue Ay. Ing. Web y Móvil

### ISSUE THREAD

**Issue by EDANHS** [sgarciaddev/ayudantia-ingweb-012024#32]
Thomas Molina

**Comment by sgarciaddev** [comment]
Hola Thomas! :hand: Bienvenido al repo de la ayudantía del curso :octocat: próximamente te daré acceso al **GitHub Project** de la ayudantía, para que le puedas pegar una mirada :100: :eyes:

Saludos! :star_struck:
