### ISSUE TITLE
Issue ING WEB y movil

### ISSUE THREAD

**Issue by GeraldEspinoza** [sgarciaddev/ayudantia-ingweb-012024#34]
Gerald Espinoza

**Comment by sgarciaddev** [comment]
Hola Gerald! :hand: Bienvenido al repo de la ayudantía del curso :octocat: próximamente te daré acceso al **GitHub Project** de la ayudantía, para que le puedas pegar una mirada :100: :eyes:

Saludos! :star_struck:
