### ISSUE TITLE
Presentación

### ISSUE THREAD

**Issue by benjadiazu** [sgarciaddev/ayudantia-ingweb-012024#7]
hola, soy Benjamín Díaz

bruh

**Comment by sgarciaddev** [comment]
Hola Benjamín! :hand: Bienvenido al repo de la ayudantía del curso :octocat: próximamente te daré acceso al **GitHub Project** de la ayudantía, para que le puedas pegar una mirada :100: :eyes:

Saludos! :star_struck:
